# Pandas and Matplotlib Homework

In [1]:
#load the libraries using the normal convention
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
##prevent plotting errors
%matplotlib inline

In [2]:
#Load our excel files of interest into pandas
NHL_Goalies = pd.read_excel('NHLGoalies2016_2017.xls',na_values='',sheet_name=0) 
GAA_ = pd.read_excel('NHLGoalies2016_2017.xls',na_values='',sheet_name='5vs5')

#Appendix:
 1. DF = Pandas DataFrame
 2. NHL_Goalies DF = NHL_Goalies 
 3. GAA_ DF = GAA_

### Q1A) Create a new DF (*called NHL_Ones*) by:
#### Filtering the correct DF for Goalies that played 1 game <font color='red'> (GP = Games played)</font>

Notes: How would you find the 'GP' column in these files? Review from Pandas Lecture

In [3]:
#Answer 1A:

NHL_Ones = NHL_Goalies[NHL_Goalies.GP == 1]
NHL_Ones

,Last Name,First Name,Team,DOB,Birth City,S/P,Cntry,Nat,Ht,Wt,...,Cap Hit,Pace,1st,2nd,3rd,Star,GPS,Ginj,Injuries,CHIP
1,Alves,Jorge,CAR,1979-01-30,Boston,MA,USA,USA,69,185,...,NaN,0.000000,NaN,NaN,NaN,NaN,0.0,NaN,NaN,
13,Campbell,Jack,LAK,1992-01-09,Port Huron,MI,USA,USA,74,197,...,NaN,96.000000,NaN,NaN,NaN,NaN,0.1,NaN,NaN,
14,Comrie,Eric,WPG,1995-07-06,Edmonton,AB,CAN,CAN,73,175,...,645000.0,124.451939,NaN,NaN,NaN,NaN,0.2,NaN,NaN,
16,Copley,Pheonix,STL,1992-01-18,North Pole,AK,USA,USA,76,196,...,708750.0,104.864253,NaN,NaN,NaN,NaN,-0.1,NaN,NaN,
22,Driedger,Chris,OTT,1994-05-18,Winnipeg,MB,CAN,CAN,76,205,...,755000.0,123.000000,NaN,NaN,NaN,NaN,-0.2,NaN,NaN,
27,Forsberg,Anton,CBJ,1992-11-27,Härnösand,NaN,SWE,SWE,75,192,...,650000.0,110.611664,NaN,NaN,NaN,NaN,0.0,NaN,NaN,
29,Gillies,Jon,CGY,1994-01-22,Concord,NH,USA,USA,78,223,...,925000.0,109.000000,1.0,0.0,0.0,1.0,0.3,NaN,NaN,
32,Gudlevskis,Kristers,TBL,1992-07-31,Aizkraukle,NaN,LVA,LVA,75,223,...,NaN,125.764192,NaN,NaN,NaN,NaN,0.0,NaN,NaN,
42,Jarry,Tristan,PIT,1995-04-29,Surrey,BC,CAN,CAN,74,194,...,630833.0,107.234043,NaN,NaN,NaN,NaN,0.0,NaN,NaN,
50,Langhamer,Marek,ARI,1994-07-22,Moravska Trebova,NaN,CZE,CZE,74,193,...,648333.0,88.936627,NaN,NaN,NaN,NaN,0.0,NaN,NaN,
67,Nedeljkovic,Alex,CAR,1996-01-07,Parma,OH,USA,USA,72,198,...,NaN,102.170284,NaN,NaN,NaN,NaN,0.3,NaN,NaN,
80,Rittich,David,CGY,1992-08-19,Jihlava,NaN,CZE,CZE,75,202,...,NaN,108.000000,NaN,NaN,NaN,NaN,0.0,NaN,NaN,
87,Subban,Malcolm,BOS,1993-12-21,Toronto,ON,CAN,CAN,74,200,...,863333.0,107.843137,NaN,NaN,NaN,NaN,-0.1,NaN,NaN,
89,Tokarski,Dustin,ANA,1989-09-16,Watson,SK,CAN,CAN,72,205,...,NaN,91.993186,NaN,NaN,NaN,NaN,0.1,NaN,NaN,
90,Ullmark,Linus,BUF,1993-07-31,Lugnvik,NaN,SWE,SWE,76,221,...,775833.0,100.113507,NaN,NaN,NaN,NaN,0.2,NaN,NaN,

 ## Q1B) 
 #### A. Find the value of the minimum Salary for the entire dataset 
 #### B. Replace the missing values from the NHL_Ones DF with this
 #### C. Create a new DF after replacement by **adding** a column called  "Adjusted_Salary"
 #### D. I would like to only see the old "Salary" column and the "Adjusted Salary" column from the new Dataframe

#### Notes:
1. Note where the minimum Salary value is coming & where you are going to assign it to
2. Review notes from pandas **replacement**
3. Look up Numpy definition for null
4. Look up Pandas **Series** Naming 
5. Review concat function in Pandas
6. Review how to slice columns

In [4]:
#Answer 1B:
#show min salary
NHL_Minimum_Salary = np.min(NHL_Goalies.Salary)
NHL_Minimum_Salary
#replace min salary in NHL_Ones
NHL_Ones['Salary'].fillna(NHL_Minimum_Salary, inplace=True)
NHL_Ones['Salary']
#make new column and add it to a new DF
Adjusted_Salary = pd.Series(name = 'Adjusted_Salary')
NHL_Ones_2 = pd.concat([NHL_Ones, Adjusted_Salary], axis = 1)
#Indexing for specific columns
NHL_Ones_2 = NHL_Ones_2[['Salary', 'Adjusted_Salary']]
NHL_Ones_2

/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:5430: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

      Salary  Adjusted_Salary
1   575000.0              NaN
13  575000.0              NaN
14  575000.0              NaN
16  708750.0              NaN
22  780000.0              NaN
27  650000.0              NaN
29  925000.0              NaN
32  575000.0              NaN
42  575000.0              NaN
50  673334.0              NaN
67  575000.0              NaN
80  575000.0              NaN
87  832500.0              NaN
89  575000.0              NaN
90  892500.0              NaN

### Q2) A. Subset the NHL goalies data to include Goalies that played in more than 25 games AND have a GAA lower than 3.00 and store the New DF as 'workhorse'

Notes: 
1. Review notes from Pandas Lecture on creating masks
2. Internet search for Multiple Boolean indexing on multiple columns in a Pandas DataFrame

In [5]:
#Answer 2:
Mask = (NHL_Goalies['GP'] > 25) & (NHL_Goalies['GAA'] < 3.00)
DF_workhorse = NHL_Goalies[Mask]
DF_workhorse

,Last Name,First Name,Team,DOB,Birth City,S/P,Cntry,Nat,Ht,Wt,...,Cap Hit,Pace,1st,2nd,3rd,Star,GPS,Ginj,Injuries,CHIP
0,Allen,Jake,STL,1990-08-07,Fredericton,NB,CAN,CAN,74,203,...,2350000.0,104.033662,9.0,7.0,6.0,22.0,9.8,NaN,NaN,
2,Andersen,Frederik,TOR,1989-10-02,Herning,NaN,DNK,DNK,76,230,...,5000000.0,118.931391,9.0,6.0,6.0,21.0,13.1,2.0,Upper body,121951
3,Anderson,Craig,OTT,1981-05-21,Park Ridge,IL,USA,USA,74,187,...,4200000.0,114.858819,8.0,2.0,5.0,15.0,9.2,2.0,Lower body,102439
5,Bernier,Jonathan,ANA,1988-08-07,Laval,QC,CAN,CAN,72,184,...,4150000.0,113.938340,5.0,0.0,2.0,7.0,6.0,3.0,Upper body,151829
9,Bishop,Ben,"TBL, LAK",1986-11-21,Denver,CO,USA,USA,79,216,...,5950000.0,108.466747,0.0,1.0,5.0,6.0,5.7,9.0,Lower body,653049
10,Bobrovsky,Sergei,CBJ,1988-09-20,Novokuznetsk,NaN,RUS,RUS,74,182,...,7425000.0,109.525950,17.0,6.0,6.0,29.0,14.9,2.0,Illness,181098
12,Budaj,Peter,"LAK, TBL",1982-09-18,Banská Bystrica,NaN,SVK,SVK,73,196,...,600000.0,108.110995,4.0,7.0,4.0,15.0,8.6,NaN,NaN,
15,Condon,Mike,"PIT, OTT",1990-04-27,Holliston,MA,USA,USA,74,197,...,575000.0,112.079733,9.0,1.0,4.0,14.0,6.8,NaN,NaN,
18,Crawford,Corey,CHI,1984-12-31,Montreal,QC,CAN,CAN,74,216,...,6000000.0,112.428393,8.0,5.0,0.0,13.0,11.0,11.0,"Appendectomy, Illness",804878
19,Darling,Scott,CHI,1988-12-22,Newport News,VA,USA,USA,78,232,...,587500.0,109.476386,5.0,5.0,5.0,15.0,6.2,5.0,Upper body,35823.2
23,Dubnyk,Devan,MIN,1986-05-04,Regina,SK,CAN,CAN,78,213,...,4333333.0,109.334753,8.0,6.0,8.0,22.0,13.1,NaN,NaN,
24,Elliott,Brian,CGY,1985-04-09,Newmarket,ON,CAN,CAN,74,209,...,2500000.0,108.444028,6.0,7.0,5.0,18.0,7.3,1.0,Illness,30487.8
28,Gibson,John,ANA,1993-07-14,Pittsburgh,PA,USA,USA,75,226,...,2300000.0,109.329402,7.0,8.0,2.0,17.0,10.3,13.0,Lowe body,364634
30,Greiss,Thomas,NYI,1986-01-29,Fussen,NaN,DEU,DEU,73,228,...,1500000.0,115.658454,2.0,6.0,6.0,14.0,8.6,NaN,NaN,
34,Halak,Jaroslav,NYI,1985-05-13,Bratislava,NaN,SVK,SVK,71,181,...,4500000.0,116.862004,4.0,1.0,1.0,6.0,5.4,NaN,NaN,
37,Hellebuyck,Connor,WPG,1993-05-19,Commerce,MI,USA,USA,76,207,...,667500.0,107.597892,7.0,1.0,2.0,10.0,8.1,NaN,NaN,
38,Holtby,Braden,WSH,1989-09-16,Lloydminster,SK,CAN,CAN,74,217,...,6100000.0,109.755899,11.0,8.0,7.0,26.0,12.3,NaN,NaN,
39,Howard,Jimmy,DET,1984-03-26,Syracuse,NY,USA,USA,73,218,...,5291667.0,104.516545,6.0,2.0,2.0,10.0,5.1,38.0,"Groin, Knee",2.45224e+06
40,Hutchinson,Michael,WPG,1990-03-02,Barrie,ON,CAN,CAN,75,202,...,1150000.0,104.430472,2.0,1.0,1.0,4.0,3.2,NaN,NaN,
41,Hutton,Carter,STL,1985-12-19,Thunder Bay,ON,CAN,CAN,73,195,...,1125000.0,104.040300,5.0,3.0,1.0,9.0,3.8,NaN,NaN,
43,Johnson,Chad,CGY,1986-06-10,Saskatoon,SK,CAN,CAN,75,196,...,1700000.0,105.771905,7.0,2.0,1.0,10.0,5.4,2.0,Lower body,41463.4
44,Jones,Martin,SJS,1990-01-10,North Vancouver,BC,CAN,CAN,76,190,...,3000000.0,114.352625,9.0,1.0,6.0,16.0,9.9,NaN,NaN,
46,Kinkaid,Keith,NJD,1989-07-04,Farmingville,NY,USA,USA,75,195,...,725000.0,105.522498,3.0,2.0,2.0,7.0,4.9,1.0,Knee,8841.46
51,Lehner,Robin,BUF,1991-07-24,Gothenburg,NaN,SWE,SWE,76,239,...,2225000.0,110.839435,3.0,5.0,5.0,13.0,12.9,7.0,"Illness, Hip, Flu, Upper body",189939
52,Lehtonen,Kari,DAL,1983-11-16,Helsinki,NaN,FIN,FIN,76,190,...,5900000.0,114.649922,5.0,3.0,3.0,11.0,7.1,NaN,NaN,
55,Lundqvist,Henrik,NYR,1982-03-02,Are,NaN,SWE,SWE,73,188,...,8500000.0,111.429541,14.0,2.0,1.0,17.0,9.1,8.0,"Flu, Hip",829268
56,Luongo,Roberto,FLA,1979-04-04,Montreal,QC,CAN,CAN,75,217,...,5333333.0,107.488861,3.0,5.0,3.0,11.0,7.4,21.0,"Undisclosed, Upper body, Lower body",1.36585e+06
57,Markstrom,Jacob,VAN,1990-01-31,Gävle,NaN,SWE,SWE,78,196,...,1550000.0,101.752570,3.0,0.0,4.0,7.0,3.8,21.0,Lower body,396951
59,Mason,Steve,PHI,1988-05-29,Oakville,ON,CAN,CAN,76,210,...,4100000.0,113.576291,3.0,6.0,6.0,15.0,8.2,1.0,Illness,50000
63,Miller,Ryan,VAN,1980-07-17,East Lansing,MI,USA,USA,74,168,...,6000000.0,106.144434,10.0,4.0,3.0,17.0,10.3,4.0,"Undisclosed, Flu, Ankle",292683
66,Murray,Matt,PIT,1994-05-25,Thunder Bay,ON,CAN,CAN,76,178,...,628333.0,115.453033,2.0,5.0,2.0,9.0,10.3,8.0,"Hand, Lower body",61300.8
68,Neuvirth,Michal,PHI,1988-03-23,Ústí nad Labem,NaN,CZE,CZE,73,209,...,1625000.0,114.444254,0.0,1.0,1.0,2.0,1.9,27.0,"Knee, Undisclosed",535061
70,Nilsson,Anders,BUF,1990-03-19,Lulea,NaN,SWE,SWE,78,229,...,1000000.0,115.654371,4.0,1.0,1.0,6.0,6.0,3.0,Undisclosed,36585.4
73,Pickard,Calvin,COL,1992-04-15,Moncton,NB,CAN,CAN,73,200,...,1000000.0,106.926059,3.0,4.0,8.0,15.0,7.1,NaN,NaN,
74,Price,Carey,MTL,1987-08-16,Anahim Lake,BC,CAN,CAN,75,226,...,6500000.0,111.371400,9.0,9.0,6.0,24.0,12.6,3.0,Flu,237805
76,Raanta,Antti,NYR,1989-05-12,Rauma,NaN,FIN,FIN,72,195,...,1000000.0,108.808739,4.0,4.0,1.0,9.0,5.4,5.0,Lower body,60975.6
77,Rask,Tuukka,BOS,1987-03-10,Savonlinna,NaN,FIN,FIN,75,176,...,7000000.0,109.563799,14.0,4.0,8.0,26.0,9.8,4.0,Lower body,341463
78,Reimer,James,FLA,1988-03-15,Morweena,MB,CAN,CAN,74,217,...,3400000.0,107.528948,3.0,5.0,5.0,13.0,8.1,3.0,Undisclosed,124390
79,Rinne,Pekka,NSH,1982-11-03,Kempele,NaN,FIN,FIN,77,217,...,7000000.0,111.598705,5.0,9.0,10.0,24.0,11.3,2.0,"Illness, Lower body",170732
82,Schneider,Cory,NJD,1986-03-18,Marblehead,MA,USA,USA,75,205,...,6000000.0,99.791717,5.0,4.0,7.0,16.0,9.5,NaN,NaN,
84,Smith,Mike,ARI,1982-03-22,Kingston,ON,CAN,CAN,76,215,...,5666667.0,115.348101,7.0,4.0,6.0,17.0,10.9,13.0,"Lower body, Illness",898374
88,Talbot,Cam,EDM,1987-07-05,Caledonia,ON,CAN,CAN,75,199,...,4166667.0,112.035398,11.0,8.0,2.0,21.0,14.0,NaN,NaN,
92,Vasilevskiy,Andrei,TBL,1994-07-25,Tyumen,NaN,RUS,RUS,75,207,...,925000.0,108.651016,4.0,8.0,2.0,14.0,9.3,NaN,NaN,
93,Ward,Cam,CAR,1984-02-29,Saskatoon,SK,CAN,CAN,73,185,...,3300000.0,108.609467,5.0,6.0,6.0,17.0,8.5,NaN,NaN,

### Q3. Create 2 python functions that: 
<br> </br>
#### A. Creates/*Returns* a new DataFrame that displays the number of missing values in every column. 
#### This new DataFrame has one new column named "Missing" with the sum of the missing values from the columns

### Notes 
***Function takes one argument: An input DataFrame***
<br> </br>
<br> </br>
** One Proposed method:**
1. Create a pandas series object from the sum of the nulls in every column (review class notes)
2. Convert the series object to a DataFrame and pass the list of column names from the input DataFrame as the index. (read Pandas Help online)
3. During the conversion of the series object to a DataFrame pass a columns argument to create a name for the new Output DataFrame's Column.

### Expected Output:
<img src='Missing_cols_expectedoutput.png'>

In [9]:
# Answer 3A: CODE HERE; Please comment each part
def Columns(DF):
    # missing column series
    missing_columns = pd.Series(data = DF.isnull().sum(), name = 'Missing')
    # DF of missing columns
    DF_2 = pd.DataFrame(missing_columns)
    return DF_2

Columns(NHL_Goalies)

                Missing
Last Name             0
First Name            0
Team                  0
DOB                   0
Birth City            0
S/P                  34
Cntry                 0
Nat                   0
Ht                    0
Wt                    0
Sh                    0
Dft Yr               17
Rd                   17
Ovrl                 17
GP                    0
GS                    0
GR                    0
W                     0
L                     0
T                     0
OTL                   0
SA                    0
SV                    0
GA                    0
SV%                   0
GAA                   0
GSAA                  0
MIN                   0
SO                    0
G                     0
...                 ...
OZS                   0
DZS                   0
NZS                   0
CF                    0
FF                    0
SF                    0
xGF                   0
GF                    0
RebF                  0
RushF                 0
SOS                   0
SOG                   0
SO SV%                0
SOW                   0
SOL                   0
NMC                  77
Status                6
Salary                6
Cap Hit               6
Pace                  0
1st                  23
2nd                  23
3rd                  23
Star                 23
GPS                   0
Ginj                 58
Injuries             58
CHIP                  0
missing_values        0
missing_values        0

[113 rows x 1 columns]

#### B. Creates a new *column* called 'missing_values' in the input DF that sums the missing values in each row.

### Notes: 
***Function takes one argument: An input DataFrame***
<br> </br>
<br> </br>
Review the Column creation method in lecture and the axis arguments needed

### Expected Output:
<img src= 'missingrows_expectedoutput.png'>

In [10]:
#Answer 3B here; Please comment each part
def Missing_values(DF):
    # missing values series
    missing_values = pd.Series(data = DF.isnull().sum(axis = 1), name = 'missing_values')
    # new DF
    DF_2 = pd.concat([DF, missing_values], axis = 1)
    return DF_2

Missing_values(NHL_Goalies)

,Last Name,First Name,Team,DOB,Birth City,S/P,Cntry,Nat,Ht,Wt,...,2nd,3rd,Star,GPS,Ginj,Injuries,CHIP,missing_values,missing_values,missing_values
0,Allen,Jake,STL,1990-08-07,Fredericton,NB,CAN,CAN,74,203,...,7.0,6.0,22.0,9.8,NaN,NaN,,3,3,3
1,Alves,Jorge,CAR,1979-01-30,Boston,MA,USA,USA,69,185,...,NaN,NaN,NaN,0.0,NaN,NaN,,18,18,18
2,Andersen,Frederik,TOR,1989-10-02,Herning,NaN,DNK,DNK,76,230,...,6.0,6.0,21.0,13.1,2.0,Upper body,121951,2,2,2
3,Anderson,Craig,OTT,1981-05-21,Park Ridge,IL,USA,USA,74,187,...,2.0,5.0,15.0,9.2,2.0,Lower body,102439,1,1,1
4,Bachman,Richard,VAN,1987-07-25,Salt Lake City,UT,USA,USA,70,183,...,0.0,1.0,2.0,1.1,NaN,NaN,,3,3,3
5,Bernier,Jonathan,ANA,1988-08-07,Laval,QC,CAN,CAN,72,184,...,0.0,2.0,7.0,6.0,3.0,Upper body,151829,1,1,1
6,Berra,Reto,FLA,1987-01-03,Bulach,NaN,CHE,CHE,76,210,...,NaN,NaN,NaN,0.2,NaN,NaN,,8,8,8
7,Berube,Jean-Francois,NYI,1991-07-13,Repentigny,QC,CAN,CAN,73,177,...,1.0,1.0,2.0,0.8,NaN,NaN,,3,3,3
8,Bibeau,Antoine,TOR,1994-05-01,Victoriaville,QC,CAN,CAN,75,210,...,NaN,NaN,NaN,0.4,NaN,NaN,,7,7,7
9,Bishop,Ben,"TBL, LAK",1986-11-21,Denver,CO,USA,USA,79,216,...,1.0,5.0,6.0,5.7,9.0,Lower body,653049,0,0,0
10,Bobrovsky,Sergei,CBJ,1988-09-20,Novokuznetsk,NaN,RUS,RUS,74,182,...,6.0,6.0,29.0,14.9,2.0,Illness,181098,4,4,4
11,Brossoit,Laurent,EDM,1993-03-23,Port Alberni,BC,CAN,CAN,75,204,...,1.0,0.0,2.0,1.2,NaN,NaN,,3,3,3
12,Budaj,Peter,"LAK, TBL",1982-09-18,Banská Bystrica,NaN,SVK,SVK,73,196,...,7.0,4.0,15.0,8.6,NaN,NaN,,4,4,4
13,Campbell,Jack,LAK,1992-01-09,Port Huron,MI,USA,USA,74,197,...,NaN,NaN,NaN,0.1,NaN,NaN,,11,11,11
14,Comrie,Eric,WPG,1995-07-06,Edmonton,AB,CAN,CAN,73,175,...,NaN,NaN,NaN,0.2,NaN,NaN,,7,7,7
15,Condon,Mike,"PIT, OTT",1990-04-27,Holliston,MA,USA,USA,74,197,...,1.0,4.0,14.0,6.8,NaN,NaN,,6,6,6
16,Copley,Pheonix,STL,1992-01-18,North Pole,AK,USA,USA,76,196,...,NaN,NaN,NaN,-0.1,NaN,NaN,,10,10,10
17,Coreau,Jared,DET,1991-11-05,Perth,ON,CAN,CAN,78,220,...,1.0,1.0,3.0,1.0,NaN,NaN,,6,6,6
18,Crawford,Corey,CHI,1984-12-31,Montreal,QC,CAN,CAN,74,216,...,5.0,0.0,13.0,11.0,11.0,"Appendectomy, Illness",804878,0,0,0
19,Darling,Scott,CHI,1988-12-22,Newport News,VA,USA,USA,78,232,...,5.0,5.0,15.0,6.2,5.0,Upper body,35823.2,1,1,1
20,Dell,Aaron,SJS,1989-05-04,Airdrie,AB,CAN,CAN,72,205,...,3.0,2.0,8.0,4.2,NaN,NaN,,6,6,6
21,Domingue,Louis,ARI,1992-03-06,St-Hyacinthe,QC,CAN,CAN,75,210,...,0.0,2.0,5.0,4.6,6.0,"Lower body, Lower body",76829.3,1,1,1
22,Driedger,Chris,OTT,1994-05-18,Winnipeg,MB,CAN,CAN,76,205,...,NaN,NaN,NaN,-0.2,NaN,NaN,,8,8,8
23,Dubnyk,Devan,MIN,1986-05-04,Regina,SK,CAN,CAN,78,213,...,6.0,8.0,22.0,13.1,NaN,NaN,,2,2,2
24,Elliott,Brian,CGY,1985-04-09,Newmarket,ON,CAN,CAN,74,209,...,7.0,5.0,18.0,7.3,1.0,Illness,30487.8,1,1,1
25,Enroth,Jhonas,TOR,1988-06-25,Stockholm,NaN,SWE,SWE,70,175,...,NaN,NaN,NaN,0.2,NaN,NaN,,8,8,8
26,Fleury,Marc-Andre,PIT,1984-11-28,Sorel,QC,CAN,CAN,74,180,...,3.0,3.0,11.0,6.4,NaN,NaN,,2,2,2
27,Forsberg,Anton,CBJ,1992-11-27,Härnösand,NaN,SWE,SWE,75,192,...,NaN,NaN,NaN,0.0,NaN,NaN,,8,8,8
28,Gibson,John,ANA,1993-07-14,Pittsburgh,PA,USA,USA,75,226,...,8.0,2.0,17.0,10.3,13.0,Lowe body,364634,1,1,1
29,Gillies,Jon,CGY,1994-01-22,Concord,NH,USA,USA,78,223,...,0.0,0.0,1.0,0.3,NaN,NaN,,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,Mrazek,Petr,DET,1992-02-14,Ostrava,NaN,CZE,CZE,74,183,...,4.0,6.0,13.0,6.5,NaN,NaN,,4,4,4
66,Murray,Matt,PIT,1994-05-25,Thunder Bay,ON,CAN,CAN,76,178,...,5.0,2.0,9.0,10.3,8.0,"Hand, Lower body",61300.8,1,1,1
67,Nedeljkovic,Alex,CAR,1996-01-07,Parma,OH,USA,USA,72,198,...,NaN,NaN,NaN,0.3,NaN,NaN,,11,11,11
68,Neuvirth,Michal,PHI,1988-03-23,Ústí nad Labem,NaN,CZE,CZE,73,209,...,1.0,1.0,2.0,1.9,27.0,"Knee, Undisclosed",535061,2,2,2
69,Niemi,Antti,DAL,1983-08-29,Vantaa,NaN,FIN,FIN,74,215,...,2.0,0.0,7.0,3.0,NaN,NaN,,6,6,6
70,Nilsson,Anders,BUF,1990-03-19,Lulea,NaN,SWE,SWE,78,229,...,1.0,1.0,6.0,6.0,3.0,Undisclosed,36585.4,2,2,2
71,Pavelec,Ondrej,WPG,1987-08-31,Kladno,NaN,CZE,CZE,75,215,...,2.0,1.0,3.0,0.7,24.0,"Lower body, Knee",1.14146e+06,2,2,2
72,Peters,Justin,ARI,1986-08-30,Blyth,ON,CAN,CAN,73,210,...,NaN,NaN,NaN,0.3,NaN,NaN,,7,7,7
73,Pickard,Calvin,COL,1992-04-15,Moncton,NB,CAN,CAN,73,200,...,4.0,8.0,15.0,7.1,NaN,NaN,,3,3,3
74,Price,Carey,MTL,1987-08-16,Anahim Lake,BC,CAN,CAN,75,226,...,9.0,6.0,24.0,12.6,3.0,Flu,237805,0,0,0
75,Quick,Jonathan,LAK,1986-01-21,Milford,CT,USA,USA,73,218,...,3.0,1.0,7.0,2.7,59.0,Lower body,4.17317e+06,1,1,1
76,Raanta,Antti,NYR,1989-05-12,Rauma,NaN,FIN,FIN,72,195,...,4.0,1.0,9.0,5.4,5.0,Lower body,60975.6,5,5,5
77,Rask,Tuukka,BOS,1987-03-10,Savonlinna,NaN,FIN,FIN,75,176,...,4.0,8.0,26.0,9.8,4.0,Lower body,341463,1,1,1
78,Reimer,James,FLA,1988-03-15,Morweena,MB,CAN,CAN,74,217,...,5.0,5.0,13.0,8.1,3.0,Undisclosed,124390,1,1,1
79,Rinne,Pekka,NSH,1982-11-03,Kempele,NaN,FIN,FIN,77,217,...,9.0,10.0,24.0,11.3,2.0,"Illness, Lower body",170732,1,1,1
80,Rittich,David,CGY,1992-08-19,Jihlava,NaN,CZE,CZE,75,202,...,NaN,NaN,NaN,0.0,NaN,NaN,,15,15,15
81,Saros,Juuse,NSH,1995-04-19,Forssa,NaN,FIN,FIN,71,180,...,1.0,5.0,10.0,4.4,NaN,NaN,,4,4,4
82,Schneider,Cory,NJD,1986-03-18,Marblehead,MA,USA,USA,75,205,...,4.0,7.0,16.0,9.5,NaN,NaN,,2,2,2
83,Smith,Jeremy,COL,1989-04-13,Dearborn,MI,USA,USA,72,177,...,0.0,1.0,1.0,0.8,NaN,NaN,,3,3,3
84,Smith,Mike,ARI,1982-03-22,Kingston,ON,CAN,CAN,76,215,...,4.0,6.0,17.0,10.9,13.0,"Lower body, Illness",898374,0,0,0
85,Stalock,Alex,MIN,1987-07-28,St. Paul,MN,USA,USA,72,187,...,0.0,1.0,1.0,0.5,NaN,NaN,,3,3,3
86,Stolarz,Anthony,PHI,1994-01-20,Edison,NJ,USA,USA,78,210,...,1.0,1.0,3.0,1.4,NaN,NaN,,3,3,3
87,Subban,Malcolm,BOS,1993-12-21,Toronto,ON,CAN,CAN,74,200,...,NaN,NaN,NaN,-0.1,NaN,NaN,,7,7,7
88,Talbot,Cam,EDM,1987-07-05,Caledonia,ON,CAN,CAN,75,199,...,8.0,2.0,21.0,14.0,NaN,NaN,,5,5,5
89,Tokarski,Dustin,ANA,1989-09-16,Watson,SK,CAN,CAN,72,205,...,NaN,NaN,NaN,0.1,NaN,NaN,,11,11,11
90,Ullmark,Linus,BUF,1993-07-31,Lugnvik,NaN,SWE,SWE,76,221,...,NaN,NaN,NaN,0.2,NaN,NaN,,8,8,8
91,Varlamov,Semyon,COL,1988-04-27,Samara,NaN,RUS,RUS,74,209,...,3.0,1.0,7.0,3.1,50.0,"Upper body, Groin, Hip",3.59756e+06,2,2,2
92,Vasilevskiy,Andrei,TBL,1994-07-25,Tyumen,NaN,RUS,RUS,75,207,...,8.0,2.0,14.0,9.3,NaN,NaN,,4,4,4
93,Ward,Cam,CAR,1984-02-29,Saskatoon,SK,CAN,CAN,73,185,...,6.0,6.0,17.0,8.5,NaN,NaN,,2,2,2
94,Zatkoff,Jeff,LAK,1987-06-09,Detroit,MI,USA,USA,74,186,...,NaN,NaN,NaN,0.4,11.0,Lower body,120732,5,5,5

### Q4) Matplotlib Question Plot in one figure and 2 side by side plots:
<br> </br>
#### A. Plot the histogram of the all the GAA of the NHL_Goalies DF  AND the goalies that played in more than 25 games with a GAA < 3.00, 
#### B. Label the Titles of the plots differently (*ie EntireSet + Subset*)
#### C. Change the color of one of the plots from the default

# Notes

1. convert your column of interest into a NumPY array (look up online for usage)
2. Review: https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.hist.html

In [ ]:
#Answer 4 here: pleae comment

#Histogram of all players + workhorses
All_GAA = np.asarray(NHL_Goalies['GAA']) #array of all
Workhorse_GAA = np.asarray(workhorse['GAA']) #array of workhorses
plt.hist([GAA_all_array, GAA_workhorse_array], label=['All', 'Workhorse']) #combined graph
plt.title('All players') #titles
plt.show() #separate graph
plt.hist(GAA_workhorse_array, color='C5') #separate graph + color change
plt.title('Workhorses') #titles
plt.show() #separate graph

### Q5) GroupBy Question
##### 1. Subset the NHL_Goalies DataFrame where Injuries is not known <font color='red'>(Injuries=NaN)</font>; 
##### 2. Use a Merge with the GAA_  DF to produce a NEW DF (*called mergedDF*) 
###### *** USE A JOIN THAT PRESERVES ORDER AND USES THE INTERSECTION OF KEYS***
###### *** USE BOTH THE LEFT AND RIGHT INDEXES AS JOIN KEYS***
##### 3. From the mergedDF keep FirstName/LastName/Team/Cntry/ SV% /GA/GAA/ TOI (note one copy for any duplicate column)
##### 4. GroupBy country on mergedDF and aggregate The Means, Mins, and Maximum of the kept columns
#### 5. Create a dataframe of the <font color='red'>TOI </font>groupby object and write it to a comma seperated value file called ('TOI_2017.csv')

## Notes:

1. Review how to create selection criteria and how aggs/joins work from lecture notes;
2. https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html
3. https://stackoverflow.com/questions/14734533/how-to-access-pandas-groupby-dataframe-by-key
4. https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.get.html

In [16]:
#Answer 5 here: please comments
#Subset the NHL_Goalies DataFrame where Injuries is not known (Injuries=NaN)
Injured = NHL_Goalies['Injuries'].isnull()
Unknown = NHL_Goalies[Injured]

# Merge (preserving order, L/R Index = true)
mergedDF = pd.merge(Unknown, GAA_, left_index = True, right_index = True)
# Subset and keep 
subset = ['First Name_x', 'Last Name_x', 'Team_x', 'Cntry', 'SV', 'GA_x', 'GAA_x', 'TOI']
mergedDF = mergedDF[subset]
# Mean/min/max
Grouped = mergedDF.groupby('Cntry').agg(['mean', 'min', 'max'])
print(Grouped)

# New DF
DF_2 = mergedDF.groupby('Cntry').agg(['mean', 'min', 'max'])
DF_2.to_csv('TOI_2017.csv')

DF_2

                SV                GA_x               GAA_x            \
              mean   min   max    mean  min  max      mean       min
Cntry
CAN     642.880000     5  1946   61.52    0  171  2.964903  0.000000
CHE     127.000000   127   127   18.00   18   18  3.449194  3.449194
CZE     351.500000     7  1317   40.25    1  145  3.660396  3.000000
DEU     934.500000   542  1327   84.50   43  126  2.363738  2.040225
FIN     777.500000   363  1395   82.75   38  151  2.845906  2.350163
LVA       3.000000     3     3    0.00    0    0  0.000000  0.000000
RUS    1357.000000  1357  1357  123.00  123  123  2.606607  2.606607
SVK    1052.000000   810  1294   97.50   75  120  2.489630  2.176366
SWE      51.250000    23   123    6.75    2   18  3.156287  1.528338
USA     353.857143     0  1618   35.50    0  163  2.106275  0.000000

                         TOI
            max         mean      min      max
Cntry
CAN    6.000000  1147.538400     6.97  3417.26
CHE    3.449194   248.430000   248.43   248.43
CZE    4.730174   594.537500     7.39  2200.09
DEU    2.687252  1628.095000   967.33  2288.86
FIN    3.297657  1377.347500   646.87  2559.68
LVA    0.000000    11.450000    11.45    11.45
RUS    2.606607  2209.610000  2209.61  2209.61
SVK    2.802894  1927.335000  1242.10  2612.57
SWE    4.096728    95.775000    47.10   211.21
USA    5.090498   596.937857     0.13  2686.76

                SV                GA_x               GAA_x            \
              mean   min   max    mean  min  max      mean       min
Cntry
CAN     642.880000     5  1946   61.52    0  171  2.964903  0.000000
CHE     127.000000   127   127   18.00   18   18  3.449194  3.449194
CZE     351.500000     7  1317   40.25    1  145  3.660396  3.000000
DEU     934.500000   542  1327   84.50   43  126  2.363738  2.040225
FIN     777.500000   363  1395   82.75   38  151  2.845906  2.350163
LVA       3.000000     3     3    0.00    0    0  0.000000  0.000000
RUS    1357.000000  1357  1357  123.00  123  123  2.606607  2.606607
SVK    1052.000000   810  1294   97.50   75  120  2.489630  2.176366
SWE      51.250000    23   123    6.75    2   18  3.156287  1.528338
USA     353.857143     0  1618   35.50    0  163  2.106275  0.000000

                         TOI
            max         mean      min      max
Cntry
CAN    6.000000  1147.538400     6.97  3417.26
CHE    3.449194   248.430000   248.43   248.43
CZE    4.730174   594.537500     7.39  2200.09
DEU    2.687252  1628.095000   967.33  2288.86
FIN    3.297657  1377.347500   646.87  2559.68
LVA    0.000000    11.450000    11.45    11.45
RUS    2.606607  2209.610000  2209.61  2209.61
SVK    2.802894  1927.335000  1242.10  2612.57
SWE    4.096728    95.775000    47.10   211.21
USA    5.090498   596.937857     0.13  2686.76

# Q6) Write a function(s)  
## that subsets a dataframe by removing rows that are WITHIN the InterQuartile Region of a specified column
<br> </br>
### The function takes as input 
##### A: Pandas_Dataframe (For example use NHL_GoaliesDF)
##### B. Column name
### Add a condition that returns an error if the Column Name chosen is not:
##### A. Numeric Dtype
##### B. Does not exist in the Numeric Columns
### The output is a DataFrame that removes rows outside of the specified columns IQR
<br> </br>
<font color='red'>**You can use smaller helper functions **<font>
<br> </br>
See --> <href>=https://en.wikipedia.org/wiki/Interquartile_range</href>
#hint: There are several pandas subfunctions that can be useful

In [ ]:
#Answer Question 6 here

***For any questions regarding this assignment please email SAMSON: <br> </br><font color='green'>sjacob210@gmail.com ***</font>